<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>


    <IsPackable>true</IsPackable>
    <IsTestProject>false</IsTestProject>
    <PackageId>Rotbarsch.Reqnroll.Bindings</PackageId>
    <Description>English Gherkin bindings for usage in a Reqnroll test project for testing OPC/UA endpoints.</Description>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>

  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Setup\**" />
    <EmbeddedResource Remove="Setup\**" />
    <None Remove="Setup\**" />
    <ReqnrollFeatureFile Remove="Setup\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../THIRD-PARTY-NOTICES.txt" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Reqnroll" Version="3.3.2" />
    <PackageReference Include="Reqnroll.NUnit" Version="3.3.2">
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rotbarsch.Reqnroll.Core\Rotbarsch.Reqnroll.Core.csproj" />
    <ProjectReference Include="..\Rotbarsch.Reqnroll.Drivers.Interfaces\Rotbarsch.Reqnroll.Drivers.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ReqnrollObsoleteCodeBehindFiles Remove="Setup\**" />
  </ItemGroup>

  <ItemGroup>
    <ReqnrollLegacyCodeBehindFiles Remove="Setup\**" />
  </ItemGroup>

</Project>
