<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>


    <IsPackable>true</IsPackable>
    <IsTestProject>false</IsTestProject>
    <PackageId>Rotbarsch.Reqnroll.Core</PackageId>
    <Description>Core functionality of Rotbarsch.Reqnroll, handling dependency injection and setup.</Description>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../THIRD-PARTY-NOTICES.txt"
          Pack="true"
          PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Reqnroll.Microsoft.Extensions.DependencyInjection" Version="3.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rotbarsch.Reqnroll.Drivers\Rotbarsch.Reqnroll.Drivers.csproj" />
    <ProjectReference Include="..\Rotbarsch.Reqnroll.Services\Rotbarsch.Reqnroll.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\"/>
    <None Include="..\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
