<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>


    <IsPackable>true</IsPackable>
    <IsTestProject>false</IsTestProject>
    <PackageId>Rotbarsch.Reqnroll.Drivers</PackageId>
    <Description>Code-behind for the Rotbarsch.Reqnroll Gherkin bindings.</Description>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../THIRD-PARTY-NOTICES.txt" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="NJsonSchema" Version="11.5.2" />
    <PackageReference Include="NUnit" Version="3.13.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rotbarsch.Reqnroll.Drivers.Interfaces\Rotbarsch.Reqnroll.Drivers.Interfaces.csproj" />
    <ProjectReference Include="..\Rotbarsch.Reqnroll.Services.Interfaces\Rotbarsch.Reqnroll.Services.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
