<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>

    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../THIRD-PARTY-NOTICES.txt"
          Pack="true"
          PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Reqnroll" Version="3.3.2" />
    <PackageReference Include="Reqnroll.NUnit" Version="3.3.2">
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rotbarsch.Reqnroll.Bindings.Interfaces\Rotbarsch.Reqnroll.Bindings.Interfaces.csproj" />
    <ProjectReference Include="..\Rotbarsch.Reqnroll.Core\Rotbarsch.Reqnroll.Core.csproj" />
    <ProjectReference Include="..\Rotbarsch.Reqnroll.Drivers.Interfaces\Rotbarsch.Reqnroll.Drivers.Interfaces.csproj" />
  </ItemGroup>

</Project>